version: '3'
services:
  echo-server:
    image: ealen/echo-server:latest
    environment:
      - ENABLE__ENVIRONMENT=true
      - ELASTIC_APM_SERVICE_NAME=$ELASTIC_APM_SERVICE_NAME
      - ELASTIC_APM_SECRET_TOKEN=$ELASTIC_APM_SECRET_TOKEN
      - ELASTIC_APM_SERVER_URL=$ELASTIC_APM_SERVER_URL
      - ELASTIC_APM_CAPTURE_BODY=$ELASTIC_APM_CAPTURE_BODY
    ports:
      - 8080:80